Repository Team-MuMuk/BE, pull requests merged in 2025-08, with the labels that each got.

#101 [SETTING] K6 부하 테스트 환경 구축
  docker-compose.k6.yml
  k6/test.js
Labels: ⚙️ SETTING

#105 [FEAT] 사용자 건강 데이터 수집 동의 여부 받기
  src/main/java/com/mumuk/domain/user/controller/MypageController.java
  src/main/java/com/mumuk/domain/user/controller/UserController.java
  src/main/java/com/mumuk/domain/user/dto/request/AuthRequest.java
  src/main/java/com/mumuk/domain/user/dto/request/UserRequest.java
  src/main/java/com/mumuk/domain/user/entity/User.java
  src/main/java/com/mumuk/domain/user/service/MypageService.java
  src/main/java/com/mumuk/domain/user/service/UserService.java
  src/main/java/com/mumuk/domain/user/service/UserServiceImpl.java
  src/main/java/com/mumuk/global/apiPayload/code/ResultCode.java
Labels: ✨ FEAT

#100 [FEAT] FCM Push 알림 구현
  .gitignore
  build.gradle
  src/main/java/com/mumuk/domain/ingredient/controller/IngredientController.java
  src/main/java/com/mumuk/domain/ingredient/converter/IngredientConverter.java
  src/main/java/com/mumuk/domain/ingredient/dto/request/IngredientRequest.java
  src/main/java/com/mumuk/domain/ingredient/dto/response/IngredientResponse.java
  src/main/java/com/mumuk/domain/ingredient/entity/Ingredient.java
  src/main/java/com/mumuk/domain/ingredient/entity/IngredientNotification.java
  src/main/java/com/mumuk/domain/ingredient/repository/IngredientRepository.java
  src/main/java/com/mumuk/domain/ingredient/service/IngredientServiceImpl.java
  src/main/java/com/mumuk/domain/notification/controller/NotificationController.java
  src/main/java/com/mumuk/domain/notification/dto/NotificationRequest.java
  src/main/java/com/mumuk/domain/notification/entity/Fcm.java
  src/main/java/com/mumuk/domain/notification/repository/NotificationRepository.java
  src/main/java/com/mumuk/domain/notification/service/FcmMessageService.java
  src/main/java/com/mumuk/domain/notification/service/IngredientExpireScheduler.java
  src/main/java/com/mumuk/domain/notification/service/NotificationService.java
  src/main/java/com/mumuk/domain/notification/service/NotificationServiceImpl.java
  src/main/java/com/mumuk/domain/user/dto/request/FCMRequest.java
  src/main/java/com/mumuk/domain/user/entity/User.java
  src/main/java/com/mumuk/domain/user/repository/UserRepository.java
  src/main/java/com/mumuk/global/apiPayload/code/ErrorCode.java
  src/main/java/com/mumuk/global/config/FCMConfig.java
  src/main/resources/application.yml
Labels: ✨ FEAT

#111 [FEAT] 사용자 건강 데이터 OCR
  build.gradle
  src/main/java/com/mumuk/domain/ocr/controller/OcrController.java
  src/main/java/com/mumuk/domain/ocr/entity/UserHealthData.java
  src/main/java/com/mumuk/domain/ocr/repository/UserHealthDataRepository.java
  src/main/java/com/mumuk/domain/ocr/service/OcrService.java
  src/main/java/com/mumuk/domain/ocr/service/OcrServiceImpl.java
  src/main/java/com/mumuk/domain/user/controller/UserController.java
  src/main/java/com/mumuk/domain/user/dto/request/UserRequest.java
  src/main/java/com/mumuk/global/apiPayload/code/ResultCode.java
  src/main/java/com/mumuk/global/client/ClovaOcrClient.java
  src/main/java/com/mumuk/global/client/NaverBlogClient.java
  src/main/java/com/mumuk/global/converter/JsonConverter.java
  src/main/java/com/mumuk/global/util/FileResourceUtil.java
  src/main/resources/application.yml
Labels: ✨ FEAT

#115 [FEAT] 자체 로그인 ID, 닉네임, 전화번호 중복 검증 과정 API 분리
  src/main/java/com/mumuk/domain/healthManagement/controller/HealthManagementController.java
  src/main/java/com/mumuk/domain/ingredient/controller/IngredientController.java
  src/main/java/com/mumuk/domain/notification/controller/NotificationController.java
  src/main/java/com/mumuk/domain/ocr/controller/OcrController.java
  src/main/java/com/mumuk/domain/recipe/controller/RecipeBlogController.java
  src/main/java/com/mumuk/domain/recipe/controller/RecipeController.java
  src/main/java/com/mumuk/domain/recipe/controller/RecipeRecommendController.java
  src/main/java/com/mumuk/domain/search/controller/SearchController.java
  src/main/java/com/mumuk/domain/user/controller/AuthController.java
  src/main/java/com/mumuk/domain/user/controller/OAuthController.java
  src/main/java/com/mumuk/domain/user/controller/UserController.java
  src/main/java/com/mumuk/domain/user/controller/UserRecipeController.java
  src/main/java/com/mumuk/domain/user/repository/UserRepository.java
  src/main/java/com/mumuk/domain/user/service/AuthService.java
  src/main/java/com/mumuk/domain/user/service/AuthServiceImpl.java
  src/main/java/com/mumuk/global/apiPayload/code/ResultCode.java
Labels: ✨ FEAT

#119 [REFACTOR] 코드 재사용성 개선, 조회 로직 개선
  src/main/java/com/mumuk/domain/recipe/controller/RecipeRecommendController.java
  src/main/java/com/mumuk/domain/recipe/repository/RecipeRepository.java
  src/main/java/com/mumuk/domain/recipe/service/RecipeRecommendServiceImpl.java
Labels: ♻️ REFACTOR

#125 [SETTING] 부하 테스트 환경에 Grafana 추가
  docker-compose.k6.yml
  grafana/provisioning/dashboards/dashboards.yml
  grafana/provisioning/dashboards/k6-influxdb.json
  grafana/provisioning/datasources/datasource.yml
Labels: ✨ Monitoring, ⚙️ SETTING

#122 [FEAT] 네이버 쇼핑 api 구현
  src/main/java/com/mumuk/domain/recipe/controller/RecipeNaverShoppingController.java
  src/main/java/com/mumuk/domain/recipe/dto/response/RecipeNaverShoppingResponse.java
  src/main/java/com/mumuk/domain/recipe/service/NaverShoppingCacheService.java
  src/main/java/com/mumuk/domain/recipe/service/NaverShoppingCacheServiceImpl.java
  src/main/java/com/mumuk/domain/recipe/service/RecipeNaverShoppingService.java
  src/main/java/com/mumuk/domain/recipe/service/RecipeNaverShoppingServiceImpl.java
  src/main/java/com/mumuk/global/apiPayload/code/ErrorCode.java
  src/main/java/com/mumuk/global/client/NaverShoppingClient.java
Labels: ✨ FEAT

#128 [FEAT] 레시피 건강 기반 추천 구현
  src/main/java/com/mumuk/domain/ocr/repository/UserHealthDataRepository.java
  src/main/java/com/mumuk/domain/recipe/controller/RecipeController.java
  src/main/java/com/mumuk/domain/recipe/controller/RecipeRecommendController.java
  src/main/java/com/mumuk/domain/recipe/converter/RecipeConverter.java
  src/main/java/com/mumuk/domain/recipe/dto/response/RecipeResponse.java
  src/main/java/com/mumuk/domain/recipe/repository/RecipeRepository.java
  src/main/java/com/mumuk/domain/recipe/service/RecipeRecommendService.java
  src/main/java/com/mumuk/domain/recipe/service/RecipeRecommendServiceImpl.java
  src/main/java/com/mumuk/domain/recipe/service/RecipeService.java
  src/main/java/com/mumuk/domain/recipe/service/RecipeServiceImpl.java
  src/main/java/com/mumuk/domain/search/controller/SearchController.java
  src/main/java/com/mumuk/domain/search/service/SearchService.java
  src/main/java/com/mumuk/domain/search/service/SearchServiceImpl.java
  src/main/java/com/mumuk/domain/search/service/TrendSearchServiceImpl.java
  src/main/java/com/mumuk/domain/user/controller/UserRecipeController.java
  src/main/java/com/mumuk/domain/user/converter/MypageConverter.java
  src/main/java/com/mumuk/domain/user/converter/UserRecipeConverter.java
  src/main/java/com/mumuk/domain/user/dto/response/UserRecipeResponse.java
  src/main/java/com/mumuk/domain/user/service/UserRecipeService.java
  src/main/java/com/mumuk/domain/user/service/UserRecipeServiceImpl.java
Labels: ✨ FEAT

#126 [FEAT] 인기 레시피 기능 구현
  src/main/java/com/mumuk/domain/search/controller/SearchController.java
  src/main/java/com/mumuk/domain/search/dto/response/SearchResponse.java
  src/main/java/com/mumuk/domain/search/service/SearchServiceImpl.java
  src/main/java/com/mumuk/domain/search/service/TrendSearchService.java
  src/main/java/com/mumuk/domain/search/service/TrendSearchServiceImpl.java
  src/main/java/com/mumuk/domain/user/controller/UserRecipeController.java
  src/main/java/com/mumuk/global/apiPayload/code/ResultCode.java
  src/main/java/com/mumuk/global/config/RedisAutocompleteInitializer.java
  src/main/resources/application.yml
Labels: ✨ FEAT

#117 [REFACTOR] 재료 수정 api 유통기한과 알림설정 수정
  src/main/java/com/mumuk/domain/ingredient/controller/IngredientController.java
  src/main/java/com/mumuk/domain/ingredient/dto/request/IngredientRequest.java
  src/main/java/com/mumuk/domain/ingredient/repository/IngredientRepository.java
  src/main/java/com/mumuk/domain/ingredient/service/IngredientService.java
  src/main/java/com/mumuk/domain/ingredient/service/IngredientServiceImpl.java
  src/main/java/com/mumuk/global/apiPayload/code/ErrorCode.java
Labels: ♻️ REFACTOR

#132 [FEAT] 레시피 이미지 추가
  src/main/java/com/mumuk/domain/recipe/controller/RecipeRecommendController.java
  src/main/java/com/mumuk/domain/recipe/dto/request/RecipeBlogImageRequest.java
  src/main/java/com/mumuk/domain/recipe/dto/response/RecipeBlogImageResponse.java
  src/main/java/com/mumuk/domain/recipe/dto/response/RecipeResponse.java
  src/main/java/com/mumuk/domain/recipe/entity/Recipe.java
  src/main/java/com/mumuk/domain/recipe/service/RecipeBlogImageAsyncService.java
  src/main/java/com/mumuk/domain/recipe/service/RecipeBlogImageAsyncServiceImpl.java
  src/main/java/com/mumuk/domain/recipe/service/RecipeBlogImageService.java
  src/main/java/com/mumuk/domain/recipe/service/RecipeBlogImageServiceImpl.java
  src/main/java/com/mumuk/domain/recipe/service/RecipeBlogServiceImpl.java
  src/main/java/com/mumuk/domain/recipe/service/RecipeRecommendService.java
  src/main/java/com/mumuk/domain/recipe/service/RecipeRecommendServiceImpl.java
Labels: ✨ FEAT

#138 [REFACTOR] 배포 워크플로우 리팩토링
  .github/workflows/mumuk-ci-cd.yml
  Dockerfile
  docker-compose.yml
  src/main/resources/static/index.html
Labels: ♻️ REFACTOR

#142 [REFACTOR] 사용하지 않는 import문 제거
  src/main/java/com/mumuk/domain/healthManagement/dto/request/HealthGoalRequest.java
  src/main/java/com/mumuk/domain/healthManagement/dto/request/UserInfoRequest.java
  src/main/java/com/mumuk/domain/healthManagement/dto/response/HealthGoalResponse.java
  src/main/java/com/mumuk/domain/healthManagement/entity/HealthGoal.java
  src/main/java/com/mumuk/domain/healthManagement/entity/UserInfo.java
  src/main/java/com/mumuk/domain/healthManagement/repository/AllergyRepository.java
  src/main/java/com/mumuk/domain/healthManagement/service/AllergyService.java
  src/main/java/com/mumuk/domain/healthManagement/service/HealthGoalServiceImpl.java
  src/main/java/com/mumuk/domain/healthManagement/service/UserInfoService.java
  src/main/java/com/mumuk/domain/search/controller/SearchController.java
  src/main/java/com/mumuk/domain/search/dto/request/SearchRequest.java
  src/main/java/com/mumuk/domain/search/dto/response/SearchResponse.java
  src/main/java/com/mumuk/domain/search/service/AutocompleteServiceImpl.java
  src/main/java/com/mumuk/domain/search/service/RecentSearchServiceImpl.java
  src/main/java/com/mumuk/domain/search/service/SearchServiceImpl.java
Labels: ♻️ REFACTOR

#145 [REFACTOR] 모델 개선 및 프롬프트 개선
  src/main/java/com/mumuk/domain/recipe/service/RecipeRecommendServiceImpl.java
  src/main/java/com/mumuk/domain/recipe/service/RecipeServiceImpl.java
  src/main/java/com/mumuk/global/client/GeminiClient.java
  src/main/java/com/mumuk/global/config/GeminiClientConfig.java
  src/main/resources/application.yml
Labels: ♻️ REFACTOR
