Repository Team-MuMuk/BE, pull requests merged in 2025-07, with the labels that each got.

#5 [SETTING][INFRA] 서버 배포 및 CI/CD 파이프라인 구축
  .github/workflows/mumuk-ci-cd.yml
  .gitignore
  Dockerfile
  docker-compose.yml
  gradlew
  gradlew.bat
  src/main/java/com/mumuk/global/config/EnvConfig.java
  src/main/resources/application-prod.yml
Labels: 🌟 INFRA, ⚙️ SETTING

#9 [FEAT] 자체 로그인/회원가입 기능 구현
  build.gradle
  src/main/java/com/mumuk/domain/user/controller/AuthController.java
  src/main/java/com/mumuk/domain/user/dto/request/AuthRequest.java
  src/main/java/com/mumuk/domain/user/dto/response/TokenResponse.java
  src/main/java/com/mumuk/domain/user/entity/User.java
  src/main/java/com/mumuk/domain/user/repository/UserRepository.java
  src/main/java/com/mumuk/domain/user/service/AuthService.java
  src/main/java/com/mumuk/domain/user/service/AuthServiceImpl.java
  src/main/java/com/mumuk/global/apiPayload/code/ErrorCode.java
  src/main/java/com/mumuk/global/apiPayload/code/ResultCode.java
  src/main/java/com/mumuk/global/apiPayload/exception/AuthException.java
  src/main/java/com/mumuk/global/apiPayload/exception/GlobalExceptionHandler.java
  src/main/java/com/mumuk/global/apiPayload/response/Response.java
  src/main/java/com/mumuk/global/config/EnvConfig.java
  src/main/java/com/mumuk/global/config/SecurityConfig.java
  src/main/java/com/mumuk/global/config/SwaggerConfig.java
  src/main/java/com/mumuk/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/mumuk/global/security/jwt/JwtAuthenticationToken.java
  src/main/java/com/mumuk/global/security/jwt/JwtTokenProvider.java
  src/main/resources/application-dev.yml
Labels: ✨ FEAT

#13 [FEAT] SMS 인증을 통한 ID/PW 찾기 기능 구현
  build.gradle
  src/main/java/com/mumuk/domain/user/controller/AuthController.java
  src/main/java/com/mumuk/domain/user/converter/TokenResponseConverter.java
  src/main/java/com/mumuk/domain/user/dto/request/AuthRequest.java
  src/main/java/com/mumuk/domain/user/entity/User.java
  src/main/java/com/mumuk/domain/user/repository/UserRepository.java
  src/main/java/com/mumuk/domain/user/service/AuthService.java
  src/main/java/com/mumuk/domain/user/service/AuthServiceImpl.java
  src/main/java/com/mumuk/global/apiPayload/code/ErrorCode.java
  src/main/java/com/mumuk/global/apiPayload/code/ResultCode.java
  src/main/java/com/mumuk/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/mumuk/global/security/jwt/JwtAuthenticationToken.java
  src/main/java/com/mumuk/global/security/jwt/JwtTokenProvider.java
  src/main/java/com/mumuk/global/util/SmsUtil.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: ✨ FEAT

#15 [FEAT] 카카오 소셜 로그인 기능 구현
  src/main/java/com/mumuk/domain/user/controller/AuthController.java
  src/main/java/com/mumuk/domain/user/controller/OAuthController.java
  src/main/java/com/mumuk/domain/user/converter/AuthConverter.java
  src/main/java/com/mumuk/domain/user/converter/OAuthConverter.java
  src/main/java/com/mumuk/domain/user/dto/response/KaKaoResponse.java
  src/main/java/com/mumuk/domain/user/dto/response/UserResponse.java
  src/main/java/com/mumuk/domain/user/entity/User.java
  src/main/java/com/mumuk/domain/user/repository/UserRepository.java
  src/main/java/com/mumuk/domain/user/service/AuthService.java
  src/main/java/com/mumuk/domain/user/service/AuthServiceImpl.java
  src/main/java/com/mumuk/domain/user/service/OAuthService.java
  src/main/java/com/mumuk/domain/user/service/OAuthServiceImpl.java
  src/main/java/com/mumuk/global/apiPayload/code/ErrorCode.java
  src/main/java/com/mumuk/global/apiPayload/exception/GlobalExceptionHandler.java
  src/main/java/com/mumuk/global/apiPayload/response/BaseResponse.java
  src/main/java/com/mumuk/global/apiPayload/response/Response.java
  src/main/java/com/mumuk/global/config/SecurityConfig.java
  src/main/java/com/mumuk/global/security/exception/AuthException.java
  src/main/java/com/mumuk/global/security/exception/AuthFailureHandler.java
  src/main/java/com/mumuk/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/mumuk/global/security/jwt/JwtTokenProvider.java
  src/main/java/com/mumuk/global/security/oauth/util/KaKaoUtil.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: ✨ FEAT

#20 [CHORE] NCP Registry 에서 DockerHub Registry 로 저장소 변경
  .github/workflows/mumuk-ci-cd.yml
  .gitignore
  docker-compose.yml
  src/main/java/com/mumuk/domain/user/entity/User.java
Labels: 🥡 CHORE

#27 [FEAT] 인증된 사용자 정보 파싱 로직 커스터마이징
  src/main/java/com/mumuk/domain/user/controller/AuthController.java
  src/main/java/com/mumuk/domain/user/controller/MypageController.java
  src/main/java/com/mumuk/domain/user/service/AuthService.java
  src/main/java/com/mumuk/domain/user/service/AuthServiceImpl.java
  src/main/java/com/mumuk/domain/user/service/MypageService.java
  src/main/java/com/mumuk/domain/user/service/MypageServiceImpl.java
  src/main/java/com/mumuk/domain/user/service/OAuthServiceImpl.java
  src/main/java/com/mumuk/global/apiPayload/code/ErrorCode.java
  src/main/java/com/mumuk/global/config/WebConfig.java
  src/main/java/com/mumuk/global/security/annotation/AuthUser.java
  src/main/java/com/mumuk/global/security/jwt/AuthUserArgumentResolver.java
  src/main/java/com/mumuk/global/security/jwt/JwtTokenProvider.java
Labels: ✨ FEAT

#39 [FEAT] 네이버 로그인 구현
  src/main/java/com/mumuk/domain/user/controller/OAuthController.java
  src/main/java/com/mumuk/domain/user/converter/OAuthConverter.java
  src/main/java/com/mumuk/domain/user/dto/response/NaverResponse.java
  src/main/java/com/mumuk/domain/user/entity/User.java
  src/main/java/com/mumuk/domain/user/service/OAuthService.java
  src/main/java/com/mumuk/domain/user/service/OAuthServiceImpl.java
  src/main/java/com/mumuk/global/apiPayload/code/ErrorCode.java
  src/main/java/com/mumuk/global/config/DataInitializer.java
  src/main/java/com/mumuk/global/config/SecurityConfig.java
  src/main/java/com/mumuk/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/mumuk/global/security/oauth/util/NaverUtil.java
  src/main/resources/application.yml
Labels: ✨ FEAT

#48 [FEAT] #47 : 경량화된 레시피 조회 API 구현
  src/main/java/com/mumuk/domain/recipe/controller/RecipeController.java
  src/main/java/com/mumuk/domain/recipe/converter/RecipeConverter.java
  src/main/java/com/mumuk/domain/recipe/dto/request/RecipeRequest.java
  src/main/java/com/mumuk/domain/recipe/dto/response/RecipeResponse.java
  src/main/java/com/mumuk/domain/recipe/entity/Recipe.java
  src/main/java/com/mumuk/domain/recipe/repository/RecipeRepository.java
  src/main/java/com/mumuk/domain/recipe/service/RecipeService.java
  src/main/java/com/mumuk/domain/recipe/service/RecipeServiceImpl.java
Labels: ✨ FEAT

#53 [FEAT] 검색 결과 반환 기능 및 인기 검색어 조회 기능 구현
  src/main/java/com/mumuk/MumukApplication.java
  src/main/java/com/mumuk/domain/allergy/controller/AllergyController.java
  src/main/java/com/mumuk/domain/recipe/repository/RecipeRepository.java
  src/main/java/com/mumuk/domain/search/controller/SearchController.java
  src/main/java/com/mumuk/domain/search/service/RecentSearchService.java
  src/main/java/com/mumuk/domain/search/service/RecentSearchServiceImpl.java
  src/main/java/com/mumuk/domain/search/service/SearchService.java
  src/main/java/com/mumuk/domain/search/service/SearchServiceImpl.java
  src/main/java/com/mumuk/domain/search/service/TrendSearchService.java
  src/main/java/com/mumuk/domain/search/service/TrendSearchServiceImpl.java
  src/main/java/com/mumuk/global/apiPayload/code/ErrorCode.java
  src/main/java/com/mumuk/global/apiPayload/code/ResultCode.java
Labels: ✨ FEAT

#54 [REFACTOR] 소셜 로그인 State 값 검증 및 환경 분리
  src/main/java/com/mumuk/domain/user/controller/OAuthController.java
  src/main/java/com/mumuk/domain/user/service/OAuthService.java
  src/main/java/com/mumuk/domain/user/service/OAuthServiceImpl.java
  src/main/java/com/mumuk/global/apiPayload/code/ErrorCode.java
  src/main/java/com/mumuk/global/security/oauth/util/KaKaoUtil.java
  src/main/java/com/mumuk/global/security/oauth/util/NaverUtil.java
  src/main/java/com/mumuk/global/security/oauth/util/StateUtil.java
  src/main/resources/application-prod.yml
Labels: ♻️ REFACTOR

#59 [FEAT]레시피 상세 페이지로 이동, 최근 레시피 조회
  src/main/java/com/mumuk/domain/user/controller/UserRecipeController.java
  src/main/java/com/mumuk/domain/user/converter/UserRecipeConverter.java
  src/main/java/com/mumuk/domain/user/dto/response/UserRecipeResponse.java
  src/main/java/com/mumuk/domain/user/dto/response/UserResponse.java
  src/main/java/com/mumuk/domain/user/entity/UserRecipe.java
  src/main/java/com/mumuk/domain/user/repository/UserRecipeRepository.java
  src/main/java/com/mumuk/domain/user/service/RecentRecipeService.java
  src/main/java/com/mumuk/domain/user/service/RecentRecipeServiceImpl.java
  src/main/java/com/mumuk/domain/user/service/UserRecipeService.java
  src/main/java/com/mumuk/domain/user/service/UserRecipeServiceImpl.java
  src/main/java/com/mumuk/global/apiPayload/code/ErrorCode.java
  src/main/java/com/mumuk/global/apiPayload/code/ResultCode.java
  src/main/resources/application.yml
Labels: ✨ FEAT

#62 [SETTING] Prometheus & Grafana 모니터링 환경 구축
  build.gradle
  docker-compose.yml
  prometheus/prometheus.yml
  src/main/resources/application.yml
Labels: ⚙️ SETTING

#65 [REFACTOR] Nginx SSL 인증서 경로 마운트
  docker-compose.yml
Labels: ♻️ REFACTOR

#66 [FEAT] 추천 레시피 기능 구현
  src/main/java/com/mumuk/domain/recipe/dto/response/RecipeResponse.java
  src/main/java/com/mumuk/domain/recipe/repository/RecipeRepository.java
  src/main/java/com/mumuk/domain/search/controller/SearchController.java
  src/main/java/com/mumuk/domain/search/service/RecommendedRecipeService.java
  src/main/java/com/mumuk/domain/search/service/RecommendedRecipeServiceImpl.java
  src/main/java/com/mumuk/domain/user/controller/UserRecipeController.java
  src/main/java/com/mumuk/domain/user/service/UserRecipeService.java
  src/main/java/com/mumuk/domain/user/service/UserRecipeServiceImpl.java
  src/main/java/com/mumuk/global/apiPayload/code/ErrorCode.java
  src/main/java/com/mumuk/global/apiPayload/code/ResultCode.java
Labels: ✨ FEAT

#69 [REFACTOR] 레시피 상세조회에 찜 여부 추가
  src/main/java/com/mumuk/domain/user/converter/UserRecipeConverter.java
  src/main/java/com/mumuk/domain/user/dto/response/UserRecipeResponse.java
Labels: ♻️ REFACTOR

#71 [FEAT] 찜버튼 클릭, 찜한 레시피 목록 조회 구현
  src/main/java/com/mumuk/domain/user/controller/MypageController.java
  src/main/java/com/mumuk/domain/user/controller/UserRecipeController.java
  src/main/java/com/mumuk/domain/user/converter/MypageConverter.java
  src/main/java/com/mumuk/domain/user/dto/request/MypageRequest.java
  src/main/java/com/mumuk/domain/user/dto/request/UserRecipeRequest.java
  src/main/java/com/mumuk/domain/user/dto/response/UserRecipeResponse.java
  src/main/java/com/mumuk/domain/user/dto/response/UserResponse.java
  src/main/java/com/mumuk/domain/user/repository/UserRecipeRepository.java
  src/main/java/com/mumuk/domain/user/repository/UserRepository.java
  src/main/java/com/mumuk/domain/user/service/MypageService.java
  src/main/java/com/mumuk/domain/user/service/MypageServiceImpl.java
  src/main/java/com/mumuk/domain/user/service/UserRecipeService.java
  src/main/java/com/mumuk/domain/user/service/UserRecipeServiceImpl.java
  src/main/java/com/mumuk/global/apiPayload/code/ErrorCode.java
  src/main/java/com/mumuk/global/apiPayload/code/ResultCode.java
Labels: ✨ FEAT

#72 [SETTING] Prometheus 메트릭 데이터 수집 대상 추가
  docker-compose.yml
  prometheus/prometheus.yml
Labels: ⚙️ SETTING

#76 [REFACTOR] 비밀번호 확인 과정 api 분리
  src/main/java/com/mumuk/domain/user/controller/AuthController.java
  src/main/java/com/mumuk/domain/user/dto/request/AuthRequest.java
  src/main/java/com/mumuk/domain/user/service/AuthService.java
  src/main/java/com/mumuk/domain/user/service/AuthServiceImpl.java
  src/main/java/com/mumuk/global/apiPayload/code/ResultCode.java
Labels: ♻️ REFACTOR

#79 [REFACTOR] 검색 목록 반환시 찜하기 여부까지 반환하도록 수정
  src/main/java/com/mumuk/domain/search/controller/SearchController.java
  src/main/java/com/mumuk/domain/search/service/SearchService.java
  src/main/java/com/mumuk/domain/search/service/SearchServiceImpl.java
  src/main/java/com/mumuk/domain/user/repository/UserRecipeRepository.java
Labels: ♻️ REFACTOR

#86 [FIX] 파라미터 유효성 검증 오류 관련 수정
  src/main/java/com/mumuk/domain/recipe/controller/RecipeBlogController.java
Labels: 🐛 FIX

#83 [REFACTOR] 알러지 목록 토글 대신 삭제 후 재입력으로 변경
  src/main/java/com/mumuk/domain/allergy/controller/AllergyController.java
  src/main/java/com/mumuk/domain/allergy/entity/Allergy.java
  src/main/java/com/mumuk/domain/allergy/service/AllergyServiceImpl.java
Labels: ♻️ REFACTOR

#84 [FEAT] AI 기반 추천 레시피 등록 구현
  src/main/java/com/mumuk/domain/recipe/controller/RecipeController.java
  src/main/java/com/mumuk/domain/recipe/controller/RecipeRecommendController.java
  src/main/java/com/mumuk/domain/recipe/converter/RecipeConverter.java
  src/main/java/com/mumuk/domain/recipe/dto/request/HealthRecommendRequest.java
  src/main/java/com/mumuk/domain/recipe/dto/request/RecipeRequest.java
  src/main/java/com/mumuk/domain/recipe/dto/response/RecipeResponse.java
  src/main/java/com/mumuk/domain/recipe/entity/Recipe.java
  src/main/java/com/mumuk/domain/recipe/entity/RecipeCategory.java
  src/main/java/com/mumuk/domain/recipe/repository/RecipeRepository.java
  src/main/java/com/mumuk/domain/recipe/service/RecipeBlogServiceImpl.java
  src/main/java/com/mumuk/domain/recipe/service/RecipeRecommendService.java
  src/main/java/com/mumuk/domain/recipe/service/RecipeRecommendServiceImpl.java
  src/main/java/com/mumuk/domain/recipe/service/RecipeService.java
  src/main/java/com/mumuk/domain/recipe/service/RecipeServiceImpl.java
  src/main/java/com/mumuk/domain/search/service/RecommendedRecipeServiceImpl.java
  src/main/java/com/mumuk/domain/user/converter/UserRecipeConverter.java
  src/main/java/com/mumuk/domain/user/dto/response/UserRecipeResponse.java
  src/main/java/com/mumuk/global/apiPayload/code/ErrorCode.java
  src/main/java/com/mumuk/global/client/NaverBlogClient.java
  src/main/java/com/mumuk/global/client/OpenAiClient.java
  src/main/java/com/mumuk/global/security/oauth/util/KaKaoUtil.java
  src/main/java/com/mumuk/global/security/oauth/util/NaverUtil.java
  src/main/resources/application.yml
Labels: ✨ FEAT

#90 [SETTING] Loki & Grafana WAS 컨테이너 로그 모니터링 서버 구축
  docker-compose.yml
  promtail/promtail-config.yaml
Labels: ✨ Monitoring, ⚙️ SETTING

#97 [REFACTOR] 추천 검색어 반환시, 최근 조회한 레시피의 여러 카테고리들도 반영할 수 있도록 변경
  src/main/java/com/mumuk/domain/allergy/controller/AllergyController.java
  src/main/java/com/mumuk/domain/recipe/repository/RecipeRepository.java
  src/main/java/com/mumuk/domain/search/controller/SearchController.java
  src/main/java/com/mumuk/domain/search/service/RecommendedRecipeServiceImpl.java
Labels: ♻️ REFACTOR

#95 [FEAT] 레시피 수정 기능 구현
  src/main/java/com/mumuk/domain/recipe/controller/RecipeController.java
  src/main/java/com/mumuk/domain/recipe/dto/request/RecipeRequest.java
  src/main/java/com/mumuk/domain/recipe/entity/Recipe.java
  src/main/java/com/mumuk/domain/recipe/service/RecipeRecommendServiceImpl.java
  src/main/java/com/mumuk/domain/recipe/service/RecipeService.java
  src/main/java/com/mumuk/domain/recipe/service/RecipeServiceImpl.java
  src/main/java/com/mumuk/global/apiPayload/code/ResultCode.java
Labels: ✨ FEAT
